---
app:
  aws:
    enabled: true
    credential:
      id-key: "your ID"
      secret-key: "your secret"
      region: "your region"
    service:
      cloudwatch:
        enabled: true
database:
  pgsql:
    enabled: true
    uri: "postgres://webapp_user:12345678@192.168.1.203:5432/grafana?sslmode=require"
---